### ISSUE TITLE
Weird serial parser error

### ISSUE THREAD

**Issue by genepool99** [biddster/node-red-contrib-ninja#2]
I keep getting these info/error messages in my node-red log. They happen when the ninja block receives certain 433mhz sensors. Not sure what is causing them or even where to start looking. 

`11 Nov 09:10:01 - [info] [ninja-receive:836b9f30.4d1b6] Error: Error code: 1
    at raiseError (/usr/local/lib/node_modules/node-red-contrib-ninja/ninja/ninja-receive.js:90:15)
    at null.<anonymous> (/usr/local/lib/node_modules/node-red-contrib-ninja/ninja/ninja-receive.js:40:21)
    at EventEmitter.emit (events.js:95:17)
    at Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SerialInNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:126:22)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/node-red-node-serialport/25-serial.js:174:34)
    at EventEmitter.emit (events.js:117:20)
    at SerialPort.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/node-red-node-serialport/25-serial.js:263:50)
    at SerialPort.EventEmitter.emit (events.js:95:17)
    at Object.module.exports.raw [as parser] (/usr/local/lib/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/lib/parsers.js:7:13)
11 Nov 09:10:01 - [error] [ninja-receive:836b9f30.4d1b6] Error: Error code: 1
`

**Comment by biddster** [comment]
The error you're seeing would look like this from the ninja:

```
{ "ERROR": [ { "CODE": 1 } ] }
```

This node only parses what it's given so I'm pretty sure there's an internal error going on before we get to this node. 

I don't actually own a ninja block, my dad does, I wrote this blind. So I'll ping him to see if he can shed any light for you...

**Comment by mikebiddell** [comment]
Hello chaps. I don't get that error, but the link below explains that this is the arduino cloak response to anything you send it that it doesn't understand (e.g. carriage return on its own). So I believe any 433 meg signal not recognised by the cloak could cause this error code 1 response or indeed any unexpected character. http://shop.ninjablocks.com/blogs/how-to/8589165-communicating-directly-with-the-arduino-in-the-ninja-block

**Comment by genepool99** [comment]
Thanks for the info @mikebiddell and @biddster. The errors were filling up my node-red.log and making my Ninja run out of disk. I have changed the startup script to logging to file for now. It's weird because the errors happen when any of my door sensors are activated and the Ninja seems to correctly parse and send the data to the serial port.

**Comment by genepool99** [comment]
If [this ](https://github.com/ninjablocks/arduino/blob/master/NinjaObjects/NinjaObjects.cpp#L592) is the right code, it looks like the error code is most likely from an unknown vendor ID. I wish they had passed the unknown code to the error message. Short of reflashing the Arduino, it does not look like there is another way to debug it. I guess the "issue" can be closed here. Thanks again.

**Comment by biddster** [comment]
I think that probably is the code. It's disappointing there's no more info sent back as diagnosing issues like these is tricky at best.

**Comment by biddster** [comment]
Note that I've reduced the logging generated by these nodes, that will be released soon.

**Comment by genepool99** [comment]
Thanks for the new release!
